using System;
using System.Collections.Generic;

namespace Sayra.Client.Shared.Models.Recovery
{
    /// <summary>
    /// Represents a detailed, structured recovery summary report.
    /// Used by the Recovery Diagnostics Engine to document executed self-healing interventions.
    /// This model is serializable.
    /// </summary>
    public class RecoveryReport
    {
        /// <summary>
        /// Gets or sets the unique report identifier.
        /// </summary>
        public Guid ReportId { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Gets or sets the timestamp when the report was generated.
        /// </summary>
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Gets or sets the unique machine or workstation identifier.
        /// </summary>
        public string MachineId { get; set; } = Environment.MachineName;

        /// <summary>
        /// Gets or sets the client version.
        /// </summary>
        public string ClientVersion { get; set; } = "1.0.0";

        /// <summary>
        /// Gets or sets the total number of self-healing recovery actions recorded in this report.
        /// </summary>
        public int TotalRecoveryActions { get; set; }

        /// <summary>
        /// Gets or sets the number of recovery actions that successfully restored subsystem health.
        /// </summary>
        public int SuccessfulRecoveries { get; set; }

        /// <summary>
        /// Gets or sets the list of individual recovery attempts logged during the period.
        /// </summary>
        public List<RecoveryAttempt> Attempts { get; set; } = new();

        /// <summary>
        /// Gets or sets recommendations generated by the resilience diagnostics layer.
        /// </summary>
        public List<string> Recommendations { get; set; } = new();
    }
}
