namespace Sayra.Client.Shared.Models.Recovery
{
    /// <summary>
    /// Represents the distinct types of diagnostic and recovery reports generated by the resilience engine.
    /// </summary>
    public enum ReportType
    {
        /// <summary>
        /// A report generated during application startup, detailing system configuration, db integrity, and initialization status.
        /// </summary>
        Startup,

        /// <summary>
        /// A periodic health report compiling status, heartbeat state, and history for all managed subsystems.
        /// </summary>
        Health,

        /// <summary>
        /// A report compiling executed self-healing operations, outcomes, backoff state, and retry metrics.
        /// </summary>
        Recovery,

        /// <summary>
        /// A specialized report triggered by subsystem failures, capturing detailed exception logs, call stacks, and context.
        /// </summary>
        Failure,

        /// <summary>
        /// A report on system resource metrics, detailing memory, CPU, threads, handles, and low disk space warnings.
        /// </summary>
        Resource,

        /// <summary>
        /// A security-focused report detailing signature validation, policy chain audits, and media file tampering checks.
        /// </summary>
        Security
    }
}
