namespace Sayra.Client.Shared.Telemetry.Diagnostics
{
    /// <summary>
    /// Represents an actionable optimization or correction recommendation generated by the Diagnostics Engine.
    /// </summary>
    public record DiagnosticRecommendation
    {
        /// <summary>
        /// Gets the severity of the recommendation (e.g. Info, Warning, Critical).
        /// </summary>
        public string Severity { get; init; } = string.Empty;

        /// <summary>
        /// Gets the category of the recommendation (e.g. Hardware, Database, Network).
        /// </summary>
        public string Category { get; init; } = string.Empty;

        /// <summary>
        /// Gets a detailed description of the identified issue.
        /// </summary>
        public string Description { get; init; } = string.Empty;

        /// <summary>
        /// Gets the recommended actions to resolve or mitigate the issue.
        /// </summary>
        public string RecommendedAction { get; init; } = string.Empty;

        /// <summary>
        /// Gets the priority of implementing the recommendation (e.g. High, Medium, Low).
        /// </summary>
        public string Priority { get; init; } = string.Empty;

        /// <summary>
        /// Gets the name of the affected subsystem.
        /// </summary>
        public string AffectedSubsystem { get; init; } = string.Empty;

        /// <summary>
        /// Formats the recommendation into a detailed human-readable string.
        /// </summary>
        public override string ToString()
        {
            return $"[{Priority} Priority] [{Severity}] Subsystem: {AffectedSubsystem} - {Category}: {Description} | Action: {RecommendedAction}";
        }
    }
}
